### PR TITLE
Issue #48 and #51 done.

### PR DESCRIPTION
**Pull request by JeevantVerma**
Footer responsiveness improved + Footer Icons updated (manually made from scratch in figma and exported, in order to remove the blur).
Added Utkarsh Tripathi (Finance Secretary) to footer along with icon and removed GenSec phone no. Also linked both to their linkedin profiles.

+Footer on about page fixed.

### CODE REVIEW

**Comment by Siddharth-Agg-arwal** [comment]
replace the icons and center align the designations with the name if the position holder (Gensec and finsec)

**Review by Siddharth-Agg-arwal — CHANGES_REQUESTED** [review]
changes to be done in icons and alignment of designation of exbo

**Comment by JeevantVerma** [comment]
Footer updated even more

**Review by Siddharth-Agg-arwal — APPROVED** [review]

**Comment by Siddharth-Agg-arwal** [comment]
checked the responsiveness of footer and the iconography. Everything seems good. Great work Jeevant!

**Pull request merged**
